inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  TargetRailsVersion: 5.1

Rails:
  Enabled: true

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/HashSyntax:
  Enabled: false
  SupportedStyles:
    - ruby19
    - hash_rockets

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
