# Offense count: 2
Lint/HandleExceptions:
  Exclude:
    - 'lib/foreman_xen/vnc_tunnel.rb'

# Offense count: 2
Lint/RescueException:
  Exclude:
    - 'lib/foreman_xen/vnc_tunnel.rb'

# Offense count: 2
Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'app/models/foreman_xen/xenserver.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: IgnoreEmptyBlocks, AllowUnusedKeywordArguments.
Lint/UnusedBlockArgument:
  Exclude:
    - 'lib/foreman_xen/engine.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: AllowUnusedKeywordArguments, IgnoreEmptyMethods.
Lint/UnusedMethodArgument:
  Exclude:
    - 'app/models/concerns/fog_extensions/xenserver/server.rb'
    - 'app/models/foreman_xen/xenserver.rb'

# Offense count: 5
Lint/UselessAssignment:
  Exclude:
    - 'app/helpers/xen_compute_helper.rb'
    - 'lib/foreman_xen/vnc_tunnel.rb'

# Offense count: 15
Metrics/AbcSize:
  Max: 70

# Offense count: 2
Metrics/BlockNesting:
  Max: 4

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 340

# Offense count: 3
Metrics/CyclomaticComplexity:
  Max: 14

# Offense count: 19
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 42

# Offense count: 4
Metrics/PerceivedComplexity:
  Max: 15
